WebsiteBanHang/WebsiteBanHang/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: QuanLySanPham
        public ActionResult Index()
        {
            var lstSanPham = db.SanPhams.Where(x => x.DaXoa == false);
            return View(lstSanPham);
        }
        [HttpGet]
        public ActionResult TaoMoi()
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(x => x.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(x => x.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(x => x.MaNSX), "MaNSX", "TenNSX");
            return View();
        }
        SanPham ktraHinhAnhDauVao(SanPham sp,HttpPostedFileBase[] HinhAnh)
        {
            int loi = 0;
            for(int i=0;i<HinhAnh.Count();i++)
            {
                if(HinhAnh[i] !=null)
                {
                    if (HinhAnh[i].ContentLength > 0)
                    {
                        if (HinhAnh[i].ContentType != "image/jpeg" && HinhAnh[i].ContentType != "image/png" && HinhAnh[i].ContentType != "image/gif" && HinhAnh[i].ContentType != "image/jpg")
                        {
                            ViewBag.UpLoad1 = "Hình ảnh " + i + " không hợp lệ!";
                            loi++;
                            break;
                        }
                        else
                        {
                            var fileName = Path.GetFileName(HinhAnh[i].FileName);
                            var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                            if (System.IO.File.Exists(path))
                            {
                                ViewBag.Upload = "Hình ảnh " + i + " đã tồn tại!";
                                loi++;
                                break;
                            }
                        }
                    }
                }   
            }
            if (loi > 0) return null;
            ThemHinhAnhVaoFile(HinhAnh);
            sp.HinhAnh = HinhAnh[0].FileName;
            sp.HinhAnh1 = HinhAnh[1].FileName;
            sp.HinhAnh2 = HinhAnh[2].FileName;
            sp.HinhAnh3 = HinhAnh[3].FileName;
            sp.DaXoa = false;
            return sp;
        }
        int KtraLoiHinhAnh(HttpPostedFileBase[] HinhAnh)
        {
            int loi = 0;
            for (int i = 0; i < HinhAnh.Count(); i++)
            {
                if (HinhAnh[i] != null)
                {
                    if (HinhAnh[i].ContentLength > 0)
                    {
                        if (HinhAnh[i].ContentType != "image/jpeg" && HinhAnh[i].ContentType != "image/png" && HinhAnh[i].ContentType != "image/gif" && HinhAnh[i].ContentType != "image/jpg")
                        {
                            ViewBag.UpLoad1 = "Hình ảnh " + i + " không hợp lệ!";
                            loi++;
                            return loi;
                        }
                        else
                        {
                            var fileName = Path.GetFileName(HinhAnh[i].FileName);
                            var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                            if (System.IO.File.Exists(path))
                            {
                                ViewBag.Upload = "Hình ảnh " + i + " đã tồn tại!";
                                loi++;
                                return loi;
                            }
                        }
                    }
                }
            }
            return loi;
        }
        void ThemHinhAnhVaoFile(HttpPostedFileBase[] HinhAnh)
        {
            for (int i = 0; i < HinhAnh.Count(); i++)
            {
                var fileName = Path.GetFileName(HinhAnh[i].FileName);
                var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                HinhAnh[i].SaveAs(path);
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(SanPham sp, HttpPostedFileBase[] HinhAnh/*, HttpPostedFileBase HinhAnh1, HttpPostedFileBase HinhAnh2, HttpPostedFileBase HinhAnh3*/)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(x => x.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(x => x.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(x => x.MaNSX), "MaNSX", "TenNSX");

            sp = ktraHinhAnhDauVao(sp, HinhAnh);
            if(sp==null)
            {
                return View(sp);
            }
            db.SanPhams.Add(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(x => x.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            
            //load dropdownlist
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(x => x.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(x => x.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(x => x.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
            return View(sp);
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(SanPham sp, HttpPostedFileBase[] HinhAnh)
        {

            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(x => x.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(x => x.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(x => x.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);

            db.Entry(sp).State = System.Data.Entity.EntityState.Modified;
            sp = ktraHinhAnhDauVao(sp, HinhAnh);
            if (sp == null) return View(sp);

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(x => x.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }

            //load dropdownlist
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(x => x.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(x => x.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(x => x.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
            return View(sp);
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if(sp==null)
            {
                return HttpNotFound();
            }
            sp.DaXoa = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebsiteBanHang/WebsiteBanHang/Views/QuanLySanPham/ChinhSua.cshtml
@model WebsiteBanHang.Models.SanPham

@{
    ViewBag.Title = "Chỉnh sửa sản phẩm";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<link href="https://code.jquery.com/jquery-1.10.2.js">
<link href="https://code.jquery.com/ui/1.10.4/jquery-ui.js">
<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
@*Sử dụng control editor*@
<script src="~/Content/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea',
    });
</script>



<h2 style="text-align:center;margin:15px auto;color:orangered">Chỉnh sửa sản phẩm</h2>

@using (Html.BeginForm("ChinhSua", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div style="margin:10px auto">
        <div class="form-horizontal">
            <h4>Thông tin sản phẩm chọn</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <span style="color:red;">@ViewBag.UpLoad1</span><br /><br />
            @Html.Hidden("MaSP", Model.MaSP);
            <div class="form-group">
                @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayCapNhap, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (Model.NgayCapNhap != null)
                    {
                        <input type="text" name="NgayCapNhap" id="datepicker" value="@Model.NgayCapNhap.Value.ToString("dd/MM/yyyy")" class="form-control" />
                    }
                    else
                    {
                        <input type="date" name="NgayCapNhap" id="datepicker" class="form-control" />
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CauHinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea name="CauHinh">@Model.CauHinh</textarea>
                    @Html.ValidationMessageFor(model => model.CauHinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea name="MoTa">@Model.MoTa</textarea>
                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LuotXem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuotXem, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuotXem, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LuotBinhChon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuotBinhChon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuotBinhChon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LuotBinhLuan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuotBinhLuan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuotBinhLuan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLanMua, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLanMua, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLanMua, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNCC, "MaNCC", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNSX, "MaNSX", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNSX", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                    <img src="~/Content/images/@Model.HinhAnh" style="width:300px;height:250px" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                    <img src="~/Content/images/@Model.HinhAnh1" style="width:300px;height:250px" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                    <img src="~/Content/images/@Model.HinhAnh2" style="width:300px;height:250px" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                    <img src="~/Content/images/@Model.HinhAnh3" style="width:300px;height:250px" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<style>
    #CauHinh, #MoTa {
        width: 100%
    }
</style>

WebsiteBanHang/WebsiteBanHang/Views/QuanLySanPham/Index.cshtml
@using WebsiteBanHang.Models;
@model IEnumerable<SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}
    <div style="margin:20px 0;">
        @Html.ActionLink("Tạo sản phẩm mới", "TaoMoi", "", new { id = "linkTaoSPMoi" })
    </div>

@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHeader",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
        grid.Column("MaSP", "Mã SP"),
        grid.Column("TenSP", "Tên sản phẩm"),
        grid.Column("CauHinh", "Cấu hình máy", format: x => Html.Raw(x.CauHinh)),
        grid.Column("HinhAnh", "Hình ảnh", format: x => Html.Raw("<img src=\"../Content/images/" + x.HinhAnh + "\" style=\"width: 300px; height: 250px; \">")),
        grid.Column(format: x => Html.ActionLink("Sửa", "ChinhSua", new { id = x.MaSP })),
        grid.Column(format: x => Html.ActionLink("Xóa", "Xoa", new { id = x.MaSP }))
        )
    )

<style>
    .divTable {
        width: 100%;
        border: 1px solid #45484B;
    }

        .divTable td, th {
            border: 1px solid #45484B;
        }

    .gridHeader {
        background: #1BB230;
    }

        .gridHeader th a {
            color: #ffff;
        }

    .gridFooter {
        font-weight: bold;
        color: #01010B;
    }
    #linkTaoSPMoi {
        padding: 10px 16px;
        border: 1px solid #1BB230;
        background: #1BB230;
        border-radius: 5px;
        color: #ffff;
    }
        #linkTaoSPMoi:hover {
            border: 1px solid #066313;
            background: #066313;
        }
</style>

WebsiteBanHang/WebsiteBanHang/Views/QuanLySanPham/TaoMoi.cshtml
@model WebsiteBanHang.Models.SanPham

@{
    ViewBag.Title = "TaoMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
@*Sử dụng control editor*@
<script src="~/Content/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea',
    });
</script>



<h2 style="text-align:center;margin:15px auto;color:orangered">Tạo mới sản phẩm</h2>

@using (Html.BeginForm("TaoMoi", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div style="margin:10px auto">
        <div class="form-horizontal">
            <h4>Thông tin sản phẩm mới</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <span style="color:red;">@ViewBag.UpLoad1</span><br /><br />


            <div class="form-group">
                @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayCapNhap, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="NgayCapNhap" type="date" class="form-control" id="datepicker" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CauHinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea name="CauHinh"></textarea>
                    @Html.ValidationMessageFor(model => model.CauHinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea name="MoTa"></textarea>
                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LuotXem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuotXem, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuotXem, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LuotBinhChon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuotBinhChon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuotBinhChon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LuotBinhLuan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuotBinhLuan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuotBinhLuan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLanMua, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLanMua, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLanMua, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNCC, "MaNCC", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNSX, "MaNSX", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNSX", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="HinhAnh" type="file" />
                    <span style="color:red">@ViewBag.Upload</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Tạo sản phẩm mới" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<style>
    #CauHinh, #MoTa {
        width: 100%
    }
</style>